# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:

  test:
    docker:
      - image: circleci/node:8-browsers

    working_directory: ~/project

    steps:
      - checkout

      # Log the current branch
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Lint the source code
      - run:
          name: Linting
          command: npm run lint

      # Test the source code
      - run:
          name: Testing
          command: npm run ci-test

      # Build the project with AngularCLI
      - run:
          name: Build project
          command: npm run build

  build:
    docker:
      - image: circleci/node:8-browsers

    working_directory: ~/project

    steps:
      - checkout

      # Log the current branch
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Lint the source code
      - run:
          name: Linting
          command: npm run lint

      # Test the source code
      - run:
          name: Testing
          command: npm run ci-test

      # Build the project with AngularCLI
      - run:
          name: Build project
          command: npm run build

      # Tag Git version and update CHANGELOG
      - run:
          name: Release
          command: npm run release

      # Cache the dist folder for the deploy job
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist

  deploy:
    working_directory: ~/project

    docker:
      - image: circleci/node:8-browsers

    steps:
      # Log the current branch
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}

      # Restore cache from the build job which contains the
      # dist folder that needs to be deployed
      - restore_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}

      # Install AWS-CLI
      - run:
          name: Install aws cli
          command:
              sudo apt-get -y -qq install awscli

      # Deploy to S3
      - run:
          name: Deploy
          command: aws s3 sync dist/ s3://www.mubudget.tk/ --region eu-west-1 --delete

workflows:
  version: 2
  # The build and deploy workflow
  build_and_deploy:
    jobs:
      - test

      - build:
          # Deploy only from master branch
          filters:
            branches:
              only: master

      - deploy:
          requires:
            - build

          # Deploy only from master branch
          filters:
            branches:
              only: master
